### ISSUE TITLE
Record classes

### ISSUE THREAD

**Issue by dimits-ts** [arstotzkan/MapaReduce---Backend#20]
Serializable objects in the util package feature setters. If there isn't any use case where these values are retrieved, edited and saved back to persistent storage, you should consider making all their values final, removing the setters. This would benefit both debugging and the general complexity of your architecture.

If you aren't JDK constrained you should also consider using Java Records since they auto generate most boilerplate methods and ensure you don't meet any unpleasant surprises (https://www.baeldung.com/java-record-keyword).

**Comment by arstotzkan** [comment]
Planning to make attrs of GPXStatistics, GPXFile and GPXWaypoints final

Didnt have the time to do it

Thanks for the reminder

**Comment by arstotzkan** [comment]
@dimits-exe  thanks for noticing
